/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 houdini-sphere.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/houdini-sphere-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sphere.geometry} material={nodes.sphere.material} />
      <mesh geometry={nodes.spikes.geometry} material={nodes.spikes.material} />
    </group>
  )
}

useGLTF.preload('/houdini-sphere-transformed.glb')
